### ISSUE TITLE
InvalidArgumentException  : Driver [] is not supported.

### ISSUE THREAD

**Issue by ritaswc** [TELstatic/rakan#7]
/config/app.php 中的providers手动添加了
TELstatic\Rakan\RakanServiceProvider::class,

使用Storage::disk('oss')时，报错

laravel/framework v5.8.35
telstatic/rakan v2.2.1

![TIM截图20191012160228](https://user-images.githubusercontent.com/15887140/66697607-c8270600-ed09-11e9-8ea5-76723305ae2a.png)

**Comment by DeadlineSurvivor** [comment]
配置文件加下配置 filesystems.php


        'oss' => [
            'driver' => 'oss',
        ],

**Comment by ritaswc** [comment]
有空合并一下  pull request 
完善了文档中的 配置项
